### ISSUE TITLE
[FR] 시간표 등록

### ISSUE THREAD

**Issue by zero734kr** [callistoteam/schoolbot#127]
학교가 API에서 제공되지 않는 학교라면 직접 등록해서 시간표 등등 조회

예시)
```
?시간표 등록 10/21 1교시 영어
?시간표 등록 10/21 2교시 과학

?학사일정 등록 10/21 과학 시험
```

3일 후 이미 지난 날짜의 데이터는 폐기 처분

**Comment by wonderlandpark** [comment]
내장된 캘린더를 이용하시는게 나을거 같습니다.

디스코드봇에서 표시할 필요는 없어보입니다
