### ISSUE TITLE
학교 정보 제공 api 변경

### ISSUE THREAD

**Issue by wonderlandpark** [callistoteam/schoolbot#138]
[학교알리미](https://www.schoolinfo.go.kr/)

제공하는 정보가 완전 많음

쓸 수 있는거 많을듯

이 참에 neispy를 갈아업으시죠

**Comment by SaidBySolo** [comment]
https://www.schoolinfo.go.kr/ng/go/pnnggo_a01_l0.do

1. 데이터가 각학교가아닌 통합되서 나옴 -> 데이터셋
2. 문제 해결할려면 맨날 주기적으로 동기화 시켜야됨
3. 자원없음
