### ISSUE TITLE
급식 사전 렌더링

### ISSUE THREAD

**Issue by wonderlandpark** [callistoteam/schoolbot#36]
급식 사진 데이터를 이용하여, 사전 렌더링

**Comment by kijk2869** [comment]
어디서 봤는데;;

**Comment by kijk2869** [comment]
![image](https://user-images.githubusercontent.com/35522821/90946094-9ec82200-e464-11ea-86bd-98392cc7df76.png)
?

**Comment by designed-re** [comment]
이슈테러

**Comment by kijk2869** [comment]
이거 근데 진짜 넣을거면 사진 노동자 뽑아야됨

**Comment by Yoruroong** [comment]
돈주면노동함

**Comment by kijk2869** [comment]
> 돈주면노동함

@wonderlandpark 한테 받으시면 됨

**Comment by wonderlandpark** [comment]
장당 1원

**Comment by designed-re** [comment]
더올려

**Comment by wonderlandpark** [comment]
닌 뭐세요

**Comment by designed-re** [comment]
장당 10원 ㄱ

**Comment by wonderlandpark** [comment]
장당 5원

**Comment by designed-re** [comment]
에메한데 고민해봄

**Comment by kijk2869** [comment]
https://github.com/callistoteam/mealAPI/issues/1 first

**Comment by kijk2869** [comment]
Transfer to @SaidBySolo

**Comment by kijk2869** [comment]
# API Docs

BASE: `https://api.schoolbot.callisto.team`

## POST /render

### Headers
Authorization: 검열
### Querystring
meal: `Meal Name`

### Example

```
https://api.schoolbot.callisto.team/render?meal=맛있는밥&meal=정말맛있는국&meal=맛없어
```

### Response
```json
{"url": "Image URL", "ttl": 43200}
```

## For opensource user

If you want to use this api, contact to `매리#4633` as discord.

**Comment by wonderlandpark** [comment]
^^

**Comment by SaidBySolo** [comment]
2.0.0에 구현할 계획입니다.
현재 1.5.0까지의 로드맵 상에는 존재하지않습니다.

**Comment by wonderlandpark** [comment]
@SaidBySolo 아니 API만 넣으시면 되는데요?
