### ISSUE TITLE
유료 아이템

### ISSUE THREAD

**Issue by kijk2869** [callistoteam/schoolbot#80]
뭔가 할만한게 있을까?

**Comment by wonderlandpark** [comment]
아
여기 칼리스토 스토어 레포 아니구나 ㅈㅅ

**Comment by Yoruroong** [comment]
일반 유저들은 급식 이미지 화질 좀 낮추고 아이템 구매하면 원본 화질로 제공하면 될거같은데

**Comment by kijk2869** [comment]
> 대충 구상해둔거
> 
> 원더봇
> 
> 경주 스킨
> EMBED 색 커스텀
> 돈 잃는 이벤트 확률 감소

여기 스쿨봇인데요

**Comment by wonderlandpark** [comment]
최신 강남 고급 입시 정보 제공

**Comment by kijk2869** [comment]
아침마다 오늘 정보 DM주는거?

**Comment by kijk2869** [comment]
차단먹으려나?

**Comment by wonderlandpark** [comment]
그거랑 서버에다 설정하는거 ㄲ

**Comment by wonderlandpark** [comment]
DM 은 ㄴㄴ

**Comment by wonderlandpark** [comment]
차단 먹어

**Comment by Yoruroong** [comment]
구매하면 한 달에 한 번씩 수학 문제같은거 물어볼 수 있게 하는거 어떰

몰론 솔로형이 답변하고

**Comment by kijk2869** [comment]
인간콴닼ㅋㅋㅋㅋㅋ

**Comment by wonderlandpark** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by SaidBySolo** [comment]
https://www.wolframalpha.com/

2020년 9월 5일 (토) 오전 11:12, Yoru <notifications@github.com>님이 작성:

**Comment by kijk2869** [comment]
저거 유료API 일걸?

**Comment by kijk2869** [comment]
![image](https://user-images.githubusercontent.com/35522821/92295802-f7211880-ef68-11ea-9855-a9052b480fc3.png)

**Comment by SaidBySolo** [comment]
물어보지말고 쳐쓰라고

2020년 9월 5일 (토) 오전 11:14, Mary <notifications@github.com>님이 작성:
